#!/usr/bin/env node
/** Embeds bundled tick sounds as base64 for offline Web Audio decode (no fetch on iOS). */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const SOUNDS = [
  {
    src: join(root, 'public/sounds/mala.mp3'),
    out: join(root, 'constants/malaAudioData.ts'),
    constName: 'MALA_MP3_BASE64',
    note: 'original Mixkit bead click',
  },
];

for (const { src, out, constName, note } of SOUNDS) {
  if (!existsSync(src)) {
    console.warn(`Skip missing sound: ${src}`);
    continue;
  }
  const base64 = readFileSync(src).toString('base64');
  writeFileSync(
    out,
    `/** Auto-generated by scripts/embed-sounds.mjs — ${note}. */\nexport const ${constName} = '${base64}';\n`,
  );
  console.log(`Embedded ${src.split('/').pop()} (${base64.length} base64 chars) → ${out.split('/').pop()}`);
}
